import { TankType, TankDefinition, FiringPattern } from '@orris/shared';

const TANK_DEFINITIONS: Record<TankType, TankDefinition> = {
  [TankType.BASIC]: {
    type: TankType.BASIC,
    name: 'Basic',
    maxHealth: 100,
    speed: 200,
    radius: 20,
    cannonCount: 1,
    fireRate: 600,
    bulletSpeed: 400,
    bulletDamage: 20,
    bulletLifetime: 2,
    evolvesFrom: null,
    evolvesTo: [TankType.TWIN, TankType.SNIPER, TankType.MACHINE_GUN, TankType.FLANK_GUARD],
    firingPattern: FiringPattern.SINGLE,
  },
  [TankType.TWIN]: {
    type: TankType.TWIN,
    name: 'Twin',
    maxHealth: 110,
    speed: 190,
    radius: 20,
    cannonCount: 2,
    fireRate: 400,
    bulletSpeed: 380,
    bulletDamage: 15,
    bulletLifetime: 2,
    evolvesFrom: TankType.BASIC,
    evolvesTo: [TankType.TRIPLE_SHOT],
    firingPattern: FiringPattern.TWIN,
  },
  [TankType.SNIPER]: {
    type: TankType.SNIPER,
    name: 'Sniper',
    maxHealth: 90,
    speed: 180,
    radius: 18,
    cannonCount: 1,
    fireRate: 1200,
    bulletSpeed: 700,
    bulletDamage: 50,
    bulletLifetime: 3,
    evolvesFrom: TankType.BASIC,
    evolvesTo: [TankType.ASSASSIN, TankType.HUNTER],
    firingPattern: FiringPattern.SINGLE,
  },
  [TankType.MACHINE_GUN]: {
    type: TankType.MACHINE_GUN,
    name: 'Machine Gun',
    maxHealth: 100,
    speed: 195,
    radius: 20,
    cannonCount: 1,
    fireRate: 150,
    bulletSpeed: 350,
    bulletDamage: 8,
    bulletLifetime: 1.5,
    evolvesFrom: TankType.BASIC,
    evolvesTo: [TankType.DESTROYER],
    firingPattern: FiringPattern.SINGLE,
  },
  [TankType.FLANK_GUARD]: {
    type: TankType.FLANK_GUARD,
    name: 'Flank Guard',
    maxHealth: 110,
    speed: 200,
    radius: 20,
    cannonCount: 2,
    fireRate: 600,
    bulletSpeed: 380,
    bulletDamage: 18,
    bulletLifetime: 2,
    evolvesFrom: TankType.BASIC,
    evolvesTo: [TankType.OVERSEER],
    firingPattern: FiringPattern.FLANK,
  },
  [TankType.TRIPLE_SHOT]: {
    type: TankType.TRIPLE_SHOT,
    name: 'Triple Shot',
    maxHealth: 120,
    speed: 185,
    radius: 22,
    cannonCount: 3,
    fireRate: 500,
    bulletSpeed: 360,
    bulletDamage: 14,
    bulletLifetime: 2,
    evolvesFrom: TankType.TWIN,
    evolvesTo: [],
    firingPattern: FiringPattern.TRIPLE_SPREAD,
  },
  [TankType.ASSASSIN]: {
    type: TankType.ASSASSIN,
    name: 'Assassin',
    maxHealth: 80,
    speed: 220,
    radius: 16,
    cannonCount: 1,
    fireRate: 900,
    bulletSpeed: 800,
    bulletDamage: 60,
    bulletLifetime: 3.5,
    evolvesFrom: TankType.SNIPER,
    evolvesTo: [],
    firingPattern: FiringPattern.SINGLE,
  },
  [TankType.HUNTER]: {
    type: TankType.HUNTER,
    name: 'Hunter',
    maxHealth: 95,
    speed: 185,
    radius: 19,
    cannonCount: 2,
    fireRate: 800,
    bulletSpeed: 650,
    bulletDamage: 40,
    bulletLifetime: 3,
    evolvesFrom: TankType.SNIPER,
    evolvesTo: [],
    firingPattern: FiringPattern.DOUBLE_ANGLED,
  },
  [TankType.DESTROYER]: {
    type: TankType.DESTROYER,
    name: 'Destroyer',
    maxHealth: 130,
    speed: 160,
    radius: 25,
    cannonCount: 1,
    fireRate: 1500,
    bulletSpeed: 300,
    bulletDamage: 100,
    bulletLifetime: 2,
    evolvesFrom: TankType.MACHINE_GUN,
    evolvesTo: [],
    firingPattern: FiringPattern.SINGLE,
  },
  [TankType.OVERSEER]: {
    type: TankType.OVERSEER,
    name: 'Overseer',
    maxHealth: 120,
    speed: 175,
    radius: 22,
    cannonCount: 0,
    fireRate: 1000,
    bulletSpeed: 300,
    bulletDamage: 15,
    bulletLifetime: 5,
    evolvesFrom: TankType.FLANK_GUARD,
    evolvesTo: [],
    firingPattern: FiringPattern.SINGLE,
  },
};

export function getTankDefinition(type: TankType): TankDefinition {
  return TANK_DEFINITIONS[type];
}
